public class Main {
    public static void main(String[] args) {
        System.out.println("Научная библиотека: ");
        System.out.println();
        LinkedList<IBook> list1 = new LinkedList<IBook>();
        ScientificBook s1 = new ScientificBook("Александров П.С.", "Энциклопедия элементарной математики", 1150, 1951, 6);
        ScientificBook s2 = new ScientificBook("Писаревский Б.М.", "Беседы о математике и математиках", 450, 2004, 6);
        ScientificBook s3 = new ScientificBook("Соминский И.С", "Метод математической индукции", 600, 1965, 6);
        ScientificBook s4 = new ScientificBook("Пухначев Ю.В.", "Математика без формул", 200, 1977, 6);
        ScientificBook s5 = new ScientificBook("Перельман Я.И", "Живая математика", 550, 1967, 12);
        list1.addToTail(s1);
        list1.addToTail(s2);
        list1.addToTail(s3);
        list1.addToTail(s4);
        list1.addToTail(s5);
        ScientificLibraryHall hallMath = new ScientificLibraryHall("mathematics", list1);
        LinkedList<IBook> list2 = new LinkedList<IBook>();
        ScientificBook sc1 = new ScientificBook("Ланге В.Н.", "Физические парадоксы и софизмы", 340, 1978, 6);
        ScientificBook sc2 = new ScientificBook("Лауэ М.", "История физики", 270, 1956, 6);
        ScientificBook sc3 = new ScientificBook("Томсон В.", "Строение материи", 700, 1965, 6);
        list2.addToTail(sc1);
        list2.addToTail(sc2);
        list2.addToTail(sc3);
        ScientificLibraryHall hallPhys = new ScientificLibraryHall("physics", list2);
        LinkedList<IBook> list3 = new LinkedList<IBook>();
        ScientificBook sci1 = new ScientificBook("Циммер К.", "Паразиты", 800, 2011, 6);
        ScientificBook sci2 = new ScientificBook("Докинз Р.", "Расширенный фенотип", 470, 2010, 6);
        ScientificBook sci3 = new ScientificBook("Коровкин О.", "Тайны растительного мира", 610, 2010, 6);
        ScientificBook sci4 = new ScientificBook("Ридли М.", "Геном", 200, 2010, 6);
        list3.addToTail(sci1);
        list3.addToTail(sci2);
        list3.addToTail(sci3);
        list3.addToTail(sci4);
        ScientificLibraryHall hallBiol = new ScientificLibraryHall("biology", list3);
        ScientificLibraryHall[] array1 = {hallMath, hallPhys, hallBiol};
        ScientificLibrary scientific = new ScientificLibrary(array1);
        ScientificBook book1 = new ScientificBook("Шень А.", "Логарифм и экспонента", 199, 2005, 10);
        ScientificBook book2 = new ScientificBook("Шилдт Г.", "Java 8.Полное руководство", 2800, 2017, 20);

        LinkedList<IBook> list12 = new LinkedList<IBook>();
        ScientificBook s12 = new ScientificBook("Александров П.С.", "Энциклопедия элементарной математики", 1150, 1951, 6);
        ScientificBook s22 = new ScientificBook("Писаревский Б.М.", "Беседы о математике и математиках", 450, 2004, 6);
        ScientificBook s32 = new ScientificBook("Соминский И.С", "Метод математической индукции", 600, 1965, 6);
        ScientificBook s42 = new ScientificBook("Пухначев Ю.В.", "Математика без формул", 200, 1977, 6);
        ScientificBook s52 = new ScientificBook("Перельма Я.И", "Живая математика", 550, 1967, 12);
        list12.addToTail(s12);
        list12.addToTail(s22);
        list12.addToTail(s32);
        list12.addToTail(s42);
        list12.addToTail(s52);
        ScientificLibraryHall hallMath1 = new ScientificLibraryHall("mathematics", list1);

        System.out.println(hallMath.equals(hallMath1));

//        System.out.println("Добавление книги в зал...");
//        try {
//            hallMath.addBook(2, book1);
//            System.out.println("Список книг этого зала:");
//            hallMath.printName();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Удаление книги из зала...");
//            hallMath.deleteBook(2);
//            System.out.println("Список книг этого зала:");
//            hallMath.printName();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Самая дорогая книга зала: " + hallMath.getBestBook());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Сумма стоимости всех книг в библиотеке");
//            System.out.println(scientific.sumPrice());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Получение книги по ее номеру в библиотеке:");
//            System.out.println(scientific.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Сортировка книг в библиотеке по убыванию цены:");
//            scientific.printArr(scientific.sort());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Список названий залов и количества книг в них:");
//            scientific.printNameHollandNumbBook();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены книги:");
//            System.out.println(scientific.getBook(0));
//            System.out.println("После замены книги");
//            scientific.changeBook(0, book1);
//            System.out.println(scientific.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До добавления книги");
//            System.out.println(scientific.getBook(8));
//            System.out.println("После добавления книги");
//            scientific.addBook(8, book2);
//            System.out.println(scientific.getBook(8));
//            System.out.println(scientific.getBook(9));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До удаления книги");
//            System.out.println(scientific.getBook(8));
//            System.out.println(scientific.getBook(9));
//            System.out.println("После удаления книги");
//            scientific.deleteBook(8);
//            System.out.println(scientific.getBook(8));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены книги");
//            System.out.println(scientific.getBook(4));
//            System.out.println("После замены книги");
//            scientific.changeBook(4, book2);
//            System.out.println(scientific.getBook(4));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены зала");
//            System.out.println(scientific.getBook(0));
//            System.out.println();
//            System.out.println("После замены зала");
//            scientific.changeHall(0, hallPhys);
//            System.out.println(scientific.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Самая дорогая книга в библиотеке: ");
//            System.out.println(scientific.getBestBook());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Детская библиотека: ");
//            System.out.println();
        ChildrenBook[] k = new ChildrenBook[5];
        k[0] = new ChildrenBook("Льюис Кэрролл", "Алиса в стране чудес", 450, 1865, 6);
        k[1] = new ChildrenBook("Николай Носов", "Незнайка в Солнечном городе", 280, 1958, 6);
        k[2] = new ChildrenBook("Джанни Родари", "Приключения Чиполлино", 200, 1957, 6);
        k[3] = new ChildrenBook("Евгений Шварц", "Золушка", 100, 1946, 6);
        k[4] = new ChildrenBook("Ханс Кристиан Андерсен", "Русалочка", 250, 1837, 12);
        ChildrenLibraryHall hall = new ChildrenLibraryHall("hall", k);
//        ChildrenBook[] kr = new ChildrenBook[5];
//        kr[0] = new ChildrenBook("Льюис Кэрролл", "Алиса в стране чудес", 450, 1865, 6);
//        kr[1] = new ChildrenBook("Николай Носов", "Незнайка в Солнечном городе", 280, 1958, 6);
//        kr[2] = new ChildrenBook("Джанни Рода", "Приключения Чиполлино", 200, 1957, 6);
//        kr[3] = new ChildrenBook("Евгений Шварц", "Золушка", 100, 1946, 6);
//        kr[4] = new ChildrenBook("Ханс Кристиан Андерсен", "Русалочка", 250, 1837, 12);
//        ChildrenLibraryHall hall1 = new ChildrenLibraryHall("hall", kr);
        ChildrenBook[] e = new ChildrenBook[3];
        e[0] = new ChildrenBook("Шарль Перро", "Кот в сапогах", 335, 1697, 6);
        e[1] = new ChildrenBook("Корней Чуковский", "Айболит", 140, 1929, 6);
        e[2] = new ChildrenBook("Шарль Перро", "Синяя борода", 90, 1697, 12);
        ChildrenLibraryHall hall2 = new ChildrenLibraryHall("hall2", e);
        ChildrenBook[] w = new ChildrenBook[5];
        w[0] = new ChildrenBook("Корней Чуковский", "Краденое солнце", 135, 1933, 6);
        w[1] = new ChildrenBook("Братья Гримм", "Волк и семеро козлят", 140, 1812, 6);
        w[2] = new ChildrenBook("Шарль Перро", "Спящая красавица", 230, 1697, 6);
        w[3] = new ChildrenBook("Шарль Перро", "Мальчик с пальчик", 160, 1621, 6);
        w[4] = new ChildrenBook("Ханс Кристиан Андерсен", "Гадкий утёнок", 190, 1843, 6);
        ChildrenLibraryHall hall3 = new ChildrenLibraryHall("hall3", w);
        ChildrenLibraryHall[] array = {hall, hall2, hall3};
        ChildrenLibrary cl = new ChildrenLibrary(array);
        ChildrenBook q = new ChildrenBook("А.С.Пушкин", "Сказка о медведихе", 80, 1830, 6);
        ChildrenBook qwerty = new ChildrenBook("А.С.Пушкин", "Cказка о рыбаке и рыбке", 70, 1833, 6);

//        System.out.println(hall);
//        System.out.println("...");
//        System.out.println("...");
//        System.out.println(hallMath);
//        System.out.println("...");
//        System.out.println("...");
//        System.out.println(scientific);
//        System.out.println(hall.equals(hall2));
//
//            System.out.println("Добавление книги в зал...");
//            hall.addBook(2, q);
//            System.out.println("Список книг этого зала:");
//            hall.printName();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Удаление книги из зала...");
//            hall.deleteBook(2);
//            System.out.println("Список книг этого зала:");
//            hall.printName();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Самая дорогая книга зала: " + hall.getBestBook());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Сумма стоимости всех книг в библиотеке");
//            System.out.println(cl.sumPrice());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Получение книги по ее номеру в библиотеке:");
//            System.out.println(cl.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Сортировка книг в библиотеке по убыванию цены:");
//            cl.printArr(cl.sort());
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Список названий залов и количества книг в них:");
//            cl.printNameHollandNumbBook();
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены книги:");
//            System.out.println(cl.getBook(0));
//            System.out.println("После замены книги");
//            cl.changeBook(0, q);
//            System.out.println(cl.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До добавления книги");
//            System.out.println(cl.getBook(8));
//            System.out.println("После добавления книги");
//            cl.addBook(8, qwerty);
//            System.out.println(cl.getBook(8));
//            System.out.println(cl.getBook(9));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До удаления книги");
//            System.out.println(cl.getBook(8));
//            System.out.println(cl.getBook(9));
//            System.out.println("После удаления книги");
//            cl.deleteBook(8);
//            System.out.println(cl.getBook(8));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены книги");
//            System.out.println(cl.getBook(4));
//            System.out.println("После замены книги");
//            cl.changeBook(4, qwerty);
//            System.out.println(cl.getBook(4));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("До замены зала");
//            System.out.println(cl.getBook(0));
//            System.out.println();
//            System.out.println("После замены зала");
//            cl.changeHall(0, hall2);
//            System.out.println(cl.getBook(0));
//            System.out.println("...");
//            System.out.println("...");
//            System.out.println("Самая дорогая книга в библиотеке: ");
//            System.out.println(cl.getBestBook());
//        }
//        catch (BookIndexOutOfBoundsException e) {
//            System.out.println("Некоректный индекс книги!");
//        }
//        catch (HallIndexOutOfBoundsException e) {
//            System.out.println("Некорректный индекс зала!");
//        }
//        catch (InvalidBookPriceException e) {
//           System.out.println("Некорректная стоимость книги!");
//        }
//        catch (InvalidBookCountException e) {
//            System.out.println("Некорректное число книг в зале!");
//        }
//    }
    }
}